"""Video schema updated

Revision ID: 176ff3980f1b
Revises: a9f3ff931cc2
Create Date: 2024-11-21 14:42:15.590793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176ff3980f1b'
down_revision: Union[str, None] = 'a9f3ff931cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('video', 'thumbnail_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'thumbnail_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('video', 'video_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
